### ISSUE TITLE
ERROR : $hashedPassword must not be accessed before initialization in

### ISSUE THREAD

**Issue by mertgibi** [jasny/auth#17]
Hi, Trying to use the library I got such an error.Where am I doing wrong?
@jasny, @SergeAx, @Minstel 

```
Fatal error: Uncaught Error: Typed property Veloster\App\Models\User::$hashedPassword must not be accessed before initialization in C:\xampp\htdocs\php\App\Models\User.php:32
Stack trace:
#0 C:\xampp\htdocs\php\vendor\jasny\auth\src\Auth.php(319): Veloster\App\Models\User->verifyPassword('12345678')
#1 C:\xampp\htdocs\php\App\Models\Accounts.php(46): Jasny\Auth\Auth->login('admin', '12345678')
#2 C:\xampp\htdocs\php\App\Controllers\Home.php(27): Veloster\App\Models\Accounts->authenticate('admin', '12345678')
#3 [internal function]: Veloster\App\Controllers\Home::login(
#4 C:\xampp\htdocs\php\Core\Route.php(74): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\php\index.php(24): Veloster\Core\Route::dispatch()
#6 {main}
thrown in C:\xampp\htdocs\php\App\Models\User.php on line 32
```

User.php:
```
<?php

namespace Veloster\App\Models;

use Jasny\Auth;
use Jasny\Auth\UserInterface;

class User implements UserInterface
{
    public string $id;
    public string $username;
    public int $accessLevel = 0;

    protected string $hashedPassword;

    public function getAuthId(): string
    {
        return $this->id;
    }

    /**
     * {@interal This method isn't required by the interface}}.
     * @param string $password
     */
    public function changePassword(string $password): void
    {
        $this->hashedPassword = password_hash($password, PASSWORD_BCRYPT);
    }

    public function verifyPassword(string $password): bool
    {
        return password_verify($password, $this->hashedPassword);
    }

    public function getAuthChecksum(): string
    {
        return hash('sha256', $this->id . $this->hashedPassword);
    }

    public function getAuthRole(Auth\ContextInterface $context = null): int
    {
        return $this->accessLevel;
    }

    public function requiresMfa(): bool
    {
        return false;
    }
}
```

Funstion in Login_Controller.php:
```
public function authenticate(string $username,string $password)
    {
        $levels = new Authz\Levels(['user' => 1, 'moderator' => 10, 'admin' => 100]);

        $auth = new Auth($levels, new AuthStorage());

        session_start();
        $auth->initialize();
        $auth->login($username,$password);
    }
```

AuthStroge.php:
```
<?php

namespace Veloster\App\Models;

use Jasny\Auth;
use Illuminate\Database\Capsule\Manager as DB;
use Jasny\Auth\StorageInterface;

class AuthStorage implements StorageInterface
{
    /**
     * Fetch a user by ID
     * @param string $id
     * @return Auth\UserInterface|null
     */
    public function fetchUserById(string $id): ?Auth\UserInterface
    {
        DB::table('Accounts')
            ->Where('id','=', $id)
            ->get();
        return new User();
    }

    /**
     * Fetch a user by username
     * @param string $username
     * @return Auth\UserInterface|null
     */
    public function fetchUserByUsername(string $username): ?Auth\UserInterface
    {
        DB::table('Accounts')->Where('username','=', $username)->get();
        return new User;
    }

    /**
     * Fetch the context by ID.
     * @param string $id
     * @return Auth\ContextInterface|null
     */
    public function fetchContext(string $id) : ?Auth\ContextInterface
    {
        DB::table('Accounts')
            ->Where('id','=', $id)
            ->get();
        return new Context();
    }

    /**
     * Get the default context of the user.
     * @param Auth\UserInterface $user
     * @return Auth\ContextInterface|null
     */
    public function getContextForUser(Auth\UserInterface $user) : ?Auth\ContextInterface
    {
        return null;
    }
}
```

**Comment by jasny** [comment]
@Venloress please don't ping everyone that ever worked on this project. That's incredibly annoying.

**Comment by mertgibi** [comment]
I'm sorry, i just wanted help

**Comment by mertgibi** [comment]
Artık bu küütphaneyi projemde kullanmayacağım. Çok kötü

**Comment by jasny** [comment]
The `verifyPassword` method is called for a user that doesn't have password (yet). Since `hashedPassword` must be a string but isn't initialized, PHP throws an error.

For users that don't have a password, make sure `hashedPassword` is an empty string.

```php
class User implements UserInterface
{
    public string $id;
    public string $username;
    public int $accessLevel = 0;

    protected string $hashedPassword = "";

```

**Comment by Venloress** [comment]
Thanks but now i am getting this error
I guess that's the last mistake


Error:
`Fatal error: Uncaught Jasny\Auth\LoginException: Invalid credentials in C:\xampp\htdocs\php\vendor\jasny\auth\src\Auth.php:322 Stack trace: #0 C:\xampp\htdocs\php\App\Models\Accounts.php(38): Jasny\Auth\Auth->login('admin', '12345678') #1 C:\xampp\htdocs\php\App\Controllers\Home.php(27): Veloster\App\Models\Accounts->authenticate('admin', '12345678') #2 [internal function]: Veloster\App\Controllers\Home::login() #3 C:\xampp\htdocs\php\Core\Route.php(74): call_user_func_array(Array, Array) #4 C:\xampp\htdocs\php\index.php(24): Veloster\Core\Route::dispatch() #5 {main} thrown in C:\xampp\htdocs\php\vendor\jasny\auth\src\Auth.php on line 322`

Function Login in Atuh.php:
```
public function login(string $username, string $password): void
    {
        $this->assertInitialized();

        if ($this->authz->isLoggedIn()) {
            throw new \LogicException("Already logged in");
        }

        $user = $this->storage->fetchUserByUsername($username);

        if ($user === null || !$user->verifyPassword($password)) {
            print_r($user);
            $this->logger->debug("Login failed: invalid credentials", ['username' => $username]);
            throw new LoginException('Invalid credentials', LoginException::INVALID_CREDENTIALS);
        }

        if ($user->requiresMfa()) {
            $this->partialLoginUser($user);
            return;
        }

        $this->loginUser($user);
    }
```

When I print out the incoming user variable of login function:
`Veloster\App\Models\User Object ( [accessLevel] => 0 [hashedPassword:protected] => )`

**Comment by jasny** [comment]
The LoginException is thrown because the password provided to login isn't valid. You need to catch the LoginException (see https://www.php.net/manual/en/language.exceptions.php#language.exceptions.catch) and display the exception message.

Note that in case that the password for the user hasn't been set yet, and hashedPassword is an empty string, there is no valid password.

Make sure you set the password of the user (and store the hashed password to the DB).

[Arnold Daniels | Jasny - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=vvg4g)	[vvg4g]

On February 1, 2021 at 7:40 GMT, Mert Erdem <notifications@github.com> wrote:

Thanks but now i am getting this error
I guess that's the last mistake

Error:
Fatal error: Uncaught Jasny\Auth\LoginException: Invalid credentials in C:\xampp\htdocs\php\vendor\jasny\auth\src\Auth.php:322 Stack trace: #0 C:\xampp\htdocs\php\App\Models\Accounts.php(38): Jasny\Auth\Auth->login('admin', '12345678') #1 C:\xampp\htdocs\php\App\Controllers\Home.php(27): Veloster\App\Models\Accounts->authenticate('admin', '12345678') #2 [internal function]: Veloster\App\Controllers\Home::login() #3 C:\xampp\htdocs\php\Core\Route.php(74): call_user_func_array(Array, Array) #4 C:\xampp\htdocs\php\index.php(24): Veloster\Core\Route::dispatch() #5 {main} thrown in C:\xampp\htdocs\php\vendor\jasny\auth\src\Auth.php on line 322

Function Login in Atuh.php:
public function login(string $username, string $password): void { $this->assertInitialized(); if ($this->authz->isLoggedIn()) { throw new \LogicException("Already logged in"); } $user = $this->storage->fetchUserByUsername($username); if ($user === null || !$user->verifyPassword($password)) { print_r($user); $this->logger->debug("Login failed: invalid credentials", ['username' => $username]); throw new LoginException('Invalid credentials', LoginException::INVALID_CREDENTIALS); } if ($user->requiresMfa()) { $this->partialLoginUser($user); return; } $this->loginUser($user); }
When I print out the incoming user variable of login function:
Veloster\App\Models\User Object ( [accessLevel] => 0 [hashedPassword:protected] => )
